[package]
name = "deepcool-digital-linux"
version = "0.10.1"
edition = "2021"

[dependencies]
libloading = "0.8.9"
hidapi = "2.6.3"
cpu-monitor = "0.1.1"
colored = "3.0.0"
clap = { version = "4.5.51", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
