[package]
name = "deepcool-digital-linux"
version = "0.10.2"
edition = "2021"

[dependencies]
libloading = "0.9.0"
hidapi = "2.6.4"
cpu-monitor = "0.1.1"
colored = "3.0.0"

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
